import {
  AlertTriangle,
  Archive,
  Bell,
  Bookmark,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  Clipboard,
  Clock,
  Copy,
  Download,
  Edit3,
  FileText,
  Filter,
  GripVertical,
  HelpCircle,
  History,
  LayoutDashboard,
  Lightbulb,
  LoaderCircle,
  Mail,
  MoreHorizontal,
  Plus,
  Search,
  Send,
  Settings,
  Sparkles,
  Star,
  UploadCloud,
  WandSparkles,
  X,
  XCircle,
} from "lucide-react";

const icons = {
  alert: AlertTriangle,
  applied: Send,
  archive: Archive,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: BriefcaseBusiness,
  check: Check,
  checkCircle: CheckCircle2,
  clipboard: Clipboard,
  clock: Clock,
  copy: Copy,
  dashboard: LayoutDashboard,
  download: Download,
  edit: Edit3,
  file: FileText,
  filter: Filter,
  grip: GripVertical,
  help: HelpCircle,
  history: History,
  lightbulb: Lightbulb,
  loader: LoaderCircle,
  mail: Mail,
  more: MoreHorizontal,
  plus: Plus,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  star: Star,
  upload: UploadCloud,
  wand: WandSparkles,
  x: X,
  xCircle: XCircle,
};

export default function Icon({ name, size = 20, className = "", ...props }) {
  const Component = icons[name] || Sparkles;
  return <Component aria-hidden="true" className={`lucide-icon ${className}`.trim()} size={size} strokeWidth={2} {...props} />;
}
